2020-06-06T05:59:02.201354+00:00 app[web.1]: [2020-06-06 05:59:02 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-06-06T05:59:02.277686+00:00 heroku[web.1]: Process exited with status 3
2020-06-06T05:59:02.319538+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T05:59:07.000000+00:00 app[api]: Build succeeded
2020-06-06T06:01:45.000000+00:00 app[api]: Build started by user josephvcardenas@gmail.com
2020-06-06T06:02:24.380174+00:00 app[api]: Deploy 0026c25d by user josephvcardenas@gmail.com
2020-06-06T06:02:24.380174+00:00 app[api]: Release v33 created by user josephvcardenas@gmail.com
2020-06-06T06:02:24.671157+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T06:02:33.248653+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend.wsgi --log-file -`
2020-06-06T06:02:35.994810+00:00 app[web.1]: [2020-06-06 06:02:35 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T06:02:35.995983+00:00 app[web.1]: [2020-06-06 06:02:35 +0000] [4] [INFO] Listening at: http://0.0.0.0:25946 (4)
2020-06-06T06:02:35.996178+00:00 app[web.1]: [2020-06-06 06:02:35 +0000] [4] [INFO] Using worker: sync
2020-06-06T06:02:36.002278+00:00 app[web.1]: [2020-06-06 06:02:36 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T06:02:36.011166+00:00 app[web.1]: [2020-06-06 06:02:36 +0000] [9] [ERROR] Exception in worker process
2020-06-06T06:02:36.011168+00:00 app[web.1]: Traceback (most recent call last):
2020-06-06T06:02:36.011168+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-06T06:02:36.011169+00:00 app[web.1]: worker.init_process()
2020-06-06T06:02:36.011169+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-06-06T06:02:36.011170+00:00 app[web.1]: self.load_wsgi()
2020-06-06T06:02:36.011170+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-06-06T06:02:36.011170+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-06-06T06:02:36.011171+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-06-06T06:02:36.011171+00:00 app[web.1]: self.callable = self.load()
2020-06-06T06:02:36.011171+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-06-06T06:02:36.011172+00:00 app[web.1]: return self.load_wsgiapp()
2020-06-06T06:02:36.011172+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-06-06T06:02:36.011172+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-06-06T06:02:36.011173+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-06-06T06:02:36.011173+00:00 app[web.1]: mod = importlib.import_module(module)
2020-06-06T06:02:36.011173+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-06-06T06:02:36.011173+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-06-06T06:02:36.011174+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-06-06T06:02:36.011174+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-06-06T06:02:36.011174+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-06-06T06:02:36.011174+00:00 app[web.1]: ModuleNotFoundError: No module named 'django-ocr-backend.wsgi'
2020-06-06T06:02:36.011324+00:00 app[web.1]: [2020-06-06 06:02:36 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T06:02:36.053551+00:00 app[web.1]: [2020-06-06 06:02:36 +0000] [4] [INFO] Shutting down: Master
2020-06-06T06:02:36.053679+00:00 app[web.1]: [2020-06-06 06:02:36 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-06-06T06:02:36.148305+00:00 heroku[web.1]: Process exited with status 3
2020-06-06T06:02:36.215443+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-06T06:02:39.000000+00:00 app[api]: Build succeeded
2020-06-06T06:04:42.448556+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=django-ocr-backend.herokuapp.com request_id=d02ec5cc-2b6c-47b9-82ce-c38156a45b7c fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T06:04:42.943887+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=django-ocr-backend.herokuapp.com request_id=0b4460bc-52b2-47a4-8f93-1755e191650a fwd="24.18.236.208" dyno= connect= service= status=503 bytes= protocol=https
2020-06-06T06:05:29.362435+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-06T06:05:35.930359+00:00 heroku[web.1]: Starting process with command `gunicorn django-ocr-backend.wsgi --log-file -`
2020-06-06T06:05:38.305353+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-06-06T06:05:38.306391+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [4] [INFO] Listening at: http://0.0.0.0:5365 (4)
2020-06-06T06:05:38.306539+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [4] [INFO] Using worker: sync
2020-06-06T06:05:38.310501+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [9] [INFO] Booting worker with pid: 9
2020-06-06T06:05:38.316308+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [9] [ERROR] Exception in worker process
2020-06-06T06:05:38.316310+00:00 app[web.1]: Traceback (most recent call last):
2020-06-06T06:05:38.316310+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-06T06:05:38.316311+00:00 app[web.1]: worker.init_process()
2020-06-06T06:05:38.316312+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-06-06T06:05:38.316312+00:00 app[web.1]: self.load_wsgi()
2020-06-06T06:05:38.316312+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-06-06T06:05:38.316313+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-06-06T06:05:38.316313+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-06-06T06:05:38.316313+00:00 app[web.1]: self.callable = self.load()
2020-06-06T06:05:38.316314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-06-06T06:05:38.316314+00:00 app[web.1]: return self.load_wsgiapp()
2020-06-06T06:05:38.316315+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-06-06T06:05:38.316315+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-06-06T06:05:38.316315+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-06-06T06:05:38.316316+00:00 app[web.1]: mod = importlib.import_module(module)
2020-06-06T06:05:38.316316+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-06-06T06:05:38.316317+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-06-06T06:05:38.316317+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-06-06T06:05:38.316317+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-06-06T06:05:38.316318+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-06-06T06:05:38.316318+00:00 app[web.1]: ModuleNotFoundError: No module named 'django-ocr-backend.wsgi'
2020-06-06T06:05:38.316438+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-06-06T06:05:38.329014+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [10] [INFO] Booting worker with pid: 10
2020-06-06T06:05:38.334744+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [10] [ERROR] Exception in worker process
2020-06-06T06:05:38.334746+00:00 app[web.1]: Traceback (most recent call last):
2020-06-06T06:05:38.334747+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-06T06:05:38.334747+00:00 app[web.1]: worker.init_process()
2020-06-06T06:05:38.334748+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
2020-06-06T06:05:38.334748+00:00 app[web.1]: self.load_wsgi()
2020-06-06T06:05:38.334749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2020-06-06T06:05:38.334749+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2020-06-06T06:05:38.334749+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
2020-06-06T06:05:38.334750+00:00 app[web.1]: self.callable = self.load()
2020-06-06T06:05:38.334750+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2020-06-06T06:05:38.334750+00:00 app[web.1]: return self.load_wsgiapp()
2020-06-06T06:05:38.334751+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2020-06-06T06:05:38.334751+00:00 app[web.1]: return util.import_app(self.app_uri)
2020-06-06T06:05:38.334751+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
2020-06-06T06:05:38.334752+00:00 app[web.1]: mod = importlib.import_module(module)
2020-06-06T06:05:38.334752+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-06-06T06:05:38.334753+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2020-06-06T06:05:38.334753+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-06-06T06:05:38.334753+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-06-06T06:05:38.334754+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-06-06T06:05:38.334754+00:00 app[web.1]: ModuleNotFoundError: No module named 'django-ocr-backend.wsgi'
2020-06-06T06:05:38.334879+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-06-06T06:05:38.450862+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [4] [INFO] Shutting down: Master
2020-06-06T06:05:38.450973+00:00 app[web.1]: [2020-06-06 06:05:38 +0000] [4] [INFO] Reason: Worker failed to boot.
2020-06-06T06:05:38.542163+00:00 heroku[web.1]: Process exited with status 3
2020-06-06T06:05:38.582543+00:00 heroku[web.1]: State changed from starting to crashed
Terminate batch job (Y/N)? 
